//! Consumer-group and share-group heartbeat types, request builders, and
//! response converters.

use kafka_protocol::messages::{
    ApiKey, ConsumerGroupHeartbeatRequest, ConsumerGroupHeartbeatResponse, RequestHeader,
    ShareGroupHeartbeatRequest, ShareGroupHeartbeatResponse,
    consumer_group_heartbeat_request as cgh_req, consumer_group_heartbeat_response as cgh_resp,
    share_group_heartbeat_response as sgh_resp,
};
use uuid::Uuid;

use super::{
    API_VERSION_CONSUMER_GROUP_HEARTBEAT, API_VERSION_SHARE_GROUP_HEARTBEAT, group_id,
    optional_str_bytes, optional_string, optional_topic_names, request_header, str_bytes,
};

/// Topic partitions used by group heartbeat ownership or assignment payloads.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeartbeatTopicPartitions {
    /// Kafka topic UUID.
    pub topic_id: Uuid,
    /// Partition indexes.
    pub partitions: Vec<i32>,
}

impl HeartbeatTopicPartitions {
    /// Create a topic partition list.
    #[must_use]
    pub fn new<I>(topic_id: Uuid, partitions: I) -> Self
    where
        I: IntoIterator<Item = i32>,
    {
        Self {
            topic_id,
            partitions: partitions.into_iter().collect(),
        }
    }
}

/// Backwards-friendly alias for share assignment topic partitions.
#[allow(dead_code)]
pub type ShareTopicPartitions = HeartbeatTopicPartitions;

/// Options for `ConsumerGroupHeartbeat`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConsumerGroupHeartbeatOptions {
    /// Consumer group ID.
    pub group_id: String,
    /// Member ID generated by the consumer or coordinator.
    pub member_id: String,
    /// Current member epoch.
    pub member_epoch: i32,
    /// Optional static member instance ID.
    pub instance_id: Option<String>,
    /// Optional rack ID.
    pub rack_id: Option<String>,
    /// Rebalance timeout in milliseconds, or -1 when unchanged.
    pub rebalance_timeout_ms: i32,
    /// Subscribed topic names, or `None` when unchanged.
    pub subscribed_topic_names: Option<Vec<String>>,
    /// Subscribed topic regex, or `None` when unchanged.
    pub subscribed_topic_regex: Option<String>,
    /// Server-side assignor, or `None` when unchanged.
    pub server_assignor: Option<String>,
    /// Owned topic partitions, or `None` when unchanged.
    pub topic_partitions: Option<Vec<HeartbeatTopicPartitions>>,
}

impl ConsumerGroupHeartbeatOptions {
    /// Create join-heartbeat options for a consumer group member.
    #[must_use]
    pub fn new(group_id: impl Into<String>, member_id: impl Into<String>) -> Self {
        Self {
            group_id: group_id.into(),
            member_id: member_id.into(),
            member_epoch: 0,
            instance_id: None,
            rack_id: None,
            rebalance_timeout_ms: -1,
            subscribed_topic_names: None,
            subscribed_topic_regex: None,
            server_assignor: None,
            topic_partitions: None,
        }
    }
}

/// Options for `ShareGroupHeartbeat`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareGroupHeartbeatOptions {
    /// Share group ID.
    pub group_id: String,
    /// Member ID generated by the consumer.
    pub member_id: String,
    /// Current member epoch.
    pub member_epoch: i32,
    /// Optional rack ID.
    pub rack_id: Option<String>,
    /// Subscribed topic names, or `None` when unchanged.
    pub subscribed_topic_names: Option<Vec<String>>,
}

impl ShareGroupHeartbeatOptions {
    /// Create join-heartbeat options for a share group member.
    #[must_use]
    pub fn new(group_id: impl Into<String>, member_id: impl Into<String>) -> Self {
        Self {
            group_id: group_id.into(),
            member_id: member_id.into(),
            member_epoch: 0,
            rack_id: None,
            subscribed_topic_names: None,
        }
    }
}

/// Heartbeat assignment returned by consumer/share group heartbeats.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeartbeatAssignment {
    /// Assigned topic partitions.
    pub topic_partitions: Vec<HeartbeatTopicPartitions>,
}

/// Backwards-friendly alias for share heartbeat assignments.
#[allow(dead_code)]
pub type ShareAssignment = HeartbeatAssignment;

/// Parsed response from a low-level consumer/share group heartbeat.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareHeartbeatResponseData {
    /// Quota throttle time in milliseconds.
    pub throttle_time_ms: i32,
    /// Top-level broker error code.
    pub error_code: i16,
    /// Optional top-level error message.
    pub error_message: Option<String>,
    /// Member ID assigned by the coordinator.
    pub member_id: Option<String>,
    /// Member epoch assigned by the coordinator.
    pub member_epoch: i32,
    /// Heartbeat interval in milliseconds.
    pub heartbeat_interval_ms: i32,
    /// Optional assignment.
    pub assignment: Option<HeartbeatAssignment>,
}

/// Parsed response from `ConsumerGroupHeartbeat`.
pub type ConsumerGroupHeartbeatResponseData = ShareHeartbeatResponseData;

/// Parsed response from `ShareGroupHeartbeat`.
pub type ShareGroupHeartbeatResponseData = ShareHeartbeatResponseData;

/// Build a `ConsumerGroupHeartbeat` request.
pub fn build_consumer_group_heartbeat_request(
    correlation_id: i32,
    client_id: &str,
    options: &ConsumerGroupHeartbeatOptions,
) -> (RequestHeader, ConsumerGroupHeartbeatRequest) {
    let header = request_header(
        correlation_id,
        client_id,
        ApiKey::ConsumerGroupHeartbeat,
        API_VERSION_CONSUMER_GROUP_HEARTBEAT,
    );
    let request = ConsumerGroupHeartbeatRequest::default()
        .with_group_id(group_id(options.group_id.clone()))
        .with_member_id(str_bytes(options.member_id.clone()))
        .with_member_epoch(options.member_epoch)
        .with_instance_id(optional_str_bytes(options.instance_id.clone()))
        .with_rack_id(optional_str_bytes(options.rack_id.clone()))
        .with_rebalance_timeout_ms(options.rebalance_timeout_ms)
        .with_subscribed_topic_names(optional_topic_names(options.subscribed_topic_names.clone()))
        .with_subscribed_topic_regex(optional_str_bytes(options.subscribed_topic_regex.clone()))
        .with_server_assignor(optional_str_bytes(options.server_assignor.clone()))
        .with_topic_partitions(
            options
                .topic_partitions
                .as_deref()
                .map(to_consumer_request_topic_partitions),
        );

    (header, request)
}

/// Build a `ShareGroupHeartbeat` request.
pub fn build_share_group_heartbeat_request(
    correlation_id: i32,
    client_id: &str,
    options: &ShareGroupHeartbeatOptions,
) -> (RequestHeader, ShareGroupHeartbeatRequest) {
    let header = request_header(
        correlation_id,
        client_id,
        ApiKey::ShareGroupHeartbeat,
        API_VERSION_SHARE_GROUP_HEARTBEAT,
    );
    let request = ShareGroupHeartbeatRequest::default()
        .with_group_id(group_id(options.group_id.clone()))
        .with_member_id(str_bytes(options.member_id.clone()))
        .with_member_epoch(options.member_epoch)
        .with_rack_id(optional_str_bytes(options.rack_id.clone()))
        .with_subscribed_topic_names(optional_topic_names(options.subscribed_topic_names.clone()));

    (header, request)
}

/// Convert a generated `ConsumerGroupHeartbeatResponse`.
#[must_use]
pub fn convert_consumer_group_heartbeat_response(
    response: ConsumerGroupHeartbeatResponse,
) -> ConsumerGroupHeartbeatResponseData {
    ConsumerGroupHeartbeatResponseData {
        throttle_time_ms: response.throttle_time_ms,
        error_code: response.error_code,
        error_message: optional_string(response.error_message),
        member_id: optional_string(response.member_id),
        member_epoch: response.member_epoch,
        heartbeat_interval_ms: response.heartbeat_interval_ms,
        assignment: response.assignment.map(convert_consumer_assignment),
    }
}

/// Convert a generated `ShareGroupHeartbeatResponse`.
#[must_use]
pub fn convert_share_group_heartbeat_response(
    response: ShareGroupHeartbeatResponse,
) -> ShareGroupHeartbeatResponseData {
    ShareGroupHeartbeatResponseData {
        throttle_time_ms: response.throttle_time_ms,
        error_code: response.error_code,
        error_message: optional_string(response.error_message),
        member_id: optional_string(response.member_id),
        member_epoch: response.member_epoch,
        heartbeat_interval_ms: response.heartbeat_interval_ms,
        assignment: response.assignment.map(convert_share_assignment),
    }
}

fn to_consumer_request_topic_partitions(
    topics: &[HeartbeatTopicPartitions],
) -> Vec<cgh_req::TopicPartitions> {
    topics
        .iter()
        .map(|topic| {
            cgh_req::TopicPartitions::default()
                .with_topic_id(topic.topic_id)
                .with_partitions(topic.partitions.clone())
        })
        .collect()
}

fn convert_consumer_assignment(assignment: cgh_resp::Assignment) -> HeartbeatAssignment {
    HeartbeatAssignment {
        topic_partitions: assignment
            .topic_partitions
            .into_iter()
            .map(|topic| HeartbeatTopicPartitions {
                topic_id: topic.topic_id,
                partitions: topic.partitions,
            })
            .collect(),
    }
}

fn convert_share_assignment(assignment: sgh_resp::Assignment) -> HeartbeatAssignment {
    HeartbeatAssignment {
        topic_partitions: assignment
            .topic_partitions
            .into_iter()
            .map(|topic| HeartbeatTopicPartitions {
                topic_id: topic.topic_id,
                partitions: topic.partitions,
            })
            .collect(),
    }
}

#[cfg(test)]
mod tests {
    use super::super::str_bytes;
    use super::*;

    #[test]
    fn consumer_group_heartbeat_request_maps_all_optional_fields() {
        let topic_id = Uuid::from_u128(1);
        let mut options = ConsumerGroupHeartbeatOptions::new("group-a", "member-a");
        options.member_epoch = 3;
        options.instance_id = Some("instance-a".to_owned());
        options.rack_id = Some("rack-a".to_owned());
        options.rebalance_timeout_ms = 45_000;
        options.subscribed_topic_names = Some(vec!["topic-a".to_owned(), "topic-b".to_owned()]);
        options.subscribed_topic_regex = Some("topic-.*".to_owned());
        options.server_assignor = Some("range".to_owned());
        options.topic_partitions = Some(vec![HeartbeatTopicPartitions::new(topic_id, [0, 2])]);

        let (header, request) = build_consumer_group_heartbeat_request(11, "client-a", &options);

        assert_eq!(
            header.request_api_key,
            ApiKey::ConsumerGroupHeartbeat as i16
        );
        assert_eq!(
            header.request_api_version,
            API_VERSION_CONSUMER_GROUP_HEARTBEAT
        );
        assert_eq!(header.correlation_id, 11);
        assert_eq!(request.group_id.0.to_string(), "group-a");
        assert_eq!(request.member_id.to_string(), "member-a");
        assert_eq!(request.member_epoch, 3);
        assert_eq!(
            request
                .instance_id
                .as_ref()
                .map(ToString::to_string)
                .as_deref(),
            Some("instance-a")
        );
        assert_eq!(
            request.rack_id.as_ref().map(ToString::to_string).as_deref(),
            Some("rack-a")
        );
        assert_eq!(request.rebalance_timeout_ms, 45_000);
        assert_eq!(
            request
                .subscribed_topic_names
                .as_ref()
                .unwrap()
                .iter()
                .map(|topic| topic.0.to_string())
                .collect::<Vec<_>>(),
            vec!["topic-a".to_owned(), "topic-b".to_owned()]
        );
        assert_eq!(
            request
                .subscribed_topic_regex
                .as_ref()
                .map(ToString::to_string)
                .as_deref(),
            Some("topic-.*")
        );
        assert_eq!(
            request
                .server_assignor
                .as_ref()
                .map(ToString::to_string)
                .as_deref(),
            Some("range")
        );
        let partitions = request.topic_partitions.as_ref().unwrap();
        assert_eq!(partitions[0].topic_id, topic_id);
        assert_eq!(partitions[0].partitions, vec![0, 2]);
    }

    #[test]
    fn share_group_heartbeat_request_maps_topics() {
        let mut options = ShareGroupHeartbeatOptions::new("share-a", "member-b");
        options.member_epoch = -1;
        options.rack_id = Some("rack-b".to_owned());
        options.subscribed_topic_names = Some(vec!["topic-a".to_owned()]);

        let (header, request) = build_share_group_heartbeat_request(12, "client-b", &options);

        assert_eq!(header.request_api_key, ApiKey::ShareGroupHeartbeat as i16);
        assert_eq!(
            header.request_api_version,
            API_VERSION_SHARE_GROUP_HEARTBEAT
        );
        assert_eq!(request.group_id.0.to_string(), "share-a");
        assert_eq!(request.member_id.to_string(), "member-b");
        assert_eq!(request.member_epoch, -1);
        assert_eq!(
            request.rack_id.as_ref().map(ToString::to_string).as_deref(),
            Some("rack-b")
        );
        assert_eq!(
            request
                .subscribed_topic_names
                .as_ref()
                .unwrap()
                .iter()
                .map(|topic| topic.0.to_string())
                .collect::<Vec<_>>(),
            vec!["topic-a".to_owned()]
        );
    }

    #[test]
    fn consumer_group_heartbeat_response_maps_assignment() {
        let topic_id = Uuid::from_u128(5);
        let response = ConsumerGroupHeartbeatResponse::default()
            .with_throttle_time_ms(10)
            .with_error_code(0)
            .with_error_message(Some(str_bytes("ok".to_owned())))
            .with_member_id(Some(str_bytes("member-a".to_owned())))
            .with_member_epoch(6)
            .with_heartbeat_interval_ms(3_000)
            .with_assignment(Some(cgh_resp::Assignment::default().with_topic_partitions(
                vec![
                cgh_resp::TopicPartitions::default()
                    .with_topic_id(topic_id)
                    .with_partitions(vec![0, 1]),
            ],
            )));

        let converted = convert_consumer_group_heartbeat_response(response);

        assert_eq!(converted.throttle_time_ms, 10);
        assert_eq!(converted.error_message.as_deref(), Some("ok"));
        assert_eq!(converted.member_id.as_deref(), Some("member-a"));
        assert_eq!(converted.member_epoch, 6);
        assert_eq!(converted.heartbeat_interval_ms, 3_000);
        assert_eq!(
            converted.assignment.unwrap().topic_partitions,
            vec![HeartbeatTopicPartitions::new(topic_id, [0, 1])]
        );
    }
}
