//! Low-level helpers for modern consumer/share-consumer protocol messages.
//!
//! These helpers expose generated Kafka request/response shapes through crate
//! DTOs and a small client-side session helper. They do not run a background
//! fetch or acknowledgement loop.

use bytes::Bytes;
use kafka_protocol::messages::{
    ApiKey, ConsumerGroupHeartbeatRequest, ConsumerGroupHeartbeatResponse, GroupId, RequestHeader,
    ShareAcknowledgeRequest, ShareAcknowledgeResponse, ShareFetchRequest, ShareFetchResponse,
    ShareGroupHeartbeatRequest, ShareGroupHeartbeatResponse, TopicName,
    consumer_group_heartbeat_request as cgh_req, consumer_group_heartbeat_response as cgh_resp,
    share_acknowledge_request as sa_req, share_acknowledge_response as sa_resp,
    share_fetch_request as sf_req, share_fetch_response as sf_resp,
    share_group_heartbeat_response as sgh_resp,
};
use kafka_protocol::protocol::StrBytes;
use uuid::Uuid;

mod session;
pub use session::{ShareConsumerSession, ShareFetchSessionConfig};

use super::{
    API_VERSION_CONSUMER_GROUP_HEARTBEAT, API_VERSION_SHARE_ACKNOWLEDGE, API_VERSION_SHARE_FETCH,
    API_VERSION_SHARE_GROUP_HEARTBEAT,
};

/// Share acknowledgement type for a gap.
pub const SHARE_ACK_TYPE_GAP: i8 = 0;
/// Share acknowledgement type for accepted records.
pub const SHARE_ACK_TYPE_ACCEPT: i8 = 1;
/// Share acknowledgement type for released records.
pub const SHARE_ACK_TYPE_RELEASE: i8 = 2;
/// Share acknowledgement type for rejected records.
pub const SHARE_ACK_TYPE_REJECT: i8 = 3;

/// Topic partitions used by group heartbeat ownership or assignment payloads.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeartbeatTopicPartitions {
    /// Kafka topic UUID.
    pub topic_id: Uuid,
    /// Partition indexes.
    pub partitions: Vec<i32>,
}

impl HeartbeatTopicPartitions {
    /// Create a topic partition list.
    #[must_use]
    pub fn new<I>(topic_id: Uuid, partitions: I) -> Self
    where
        I: IntoIterator<Item = i32>,
    {
        Self {
            topic_id,
            partitions: partitions.into_iter().collect(),
        }
    }
}

/// Backwards-friendly alias for share assignment topic partitions.
#[allow(dead_code)]
pub type ShareTopicPartitions = HeartbeatTopicPartitions;

/// Options for `ConsumerGroupHeartbeat`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ConsumerGroupHeartbeatOptions {
    /// Consumer group ID.
    pub group_id: String,
    /// Member ID generated by the consumer or coordinator.
    pub member_id: String,
    /// Current member epoch.
    pub member_epoch: i32,
    /// Optional static member instance ID.
    pub instance_id: Option<String>,
    /// Optional rack ID.
    pub rack_id: Option<String>,
    /// Rebalance timeout in milliseconds, or -1 when unchanged.
    pub rebalance_timeout_ms: i32,
    /// Subscribed topic names, or `None` when unchanged.
    pub subscribed_topic_names: Option<Vec<String>>,
    /// Subscribed topic regex, or `None` when unchanged.
    pub subscribed_topic_regex: Option<String>,
    /// Server-side assignor, or `None` when unchanged.
    pub server_assignor: Option<String>,
    /// Owned topic partitions, or `None` when unchanged.
    pub topic_partitions: Option<Vec<HeartbeatTopicPartitions>>,
}

impl ConsumerGroupHeartbeatOptions {
    /// Create join-heartbeat options for a consumer group member.
    #[must_use]
    pub fn new(group_id: impl Into<String>, member_id: impl Into<String>) -> Self {
        Self {
            group_id: group_id.into(),
            member_id: member_id.into(),
            member_epoch: 0,
            instance_id: None,
            rack_id: None,
            rebalance_timeout_ms: -1,
            subscribed_topic_names: None,
            subscribed_topic_regex: None,
            server_assignor: None,
            topic_partitions: None,
        }
    }
}

/// Options for `ShareGroupHeartbeat`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareGroupHeartbeatOptions {
    /// Share group ID.
    pub group_id: String,
    /// Member ID generated by the consumer.
    pub member_id: String,
    /// Current member epoch.
    pub member_epoch: i32,
    /// Optional rack ID.
    pub rack_id: Option<String>,
    /// Subscribed topic names, or `None` when unchanged.
    pub subscribed_topic_names: Option<Vec<String>>,
}

impl ShareGroupHeartbeatOptions {
    /// Create join-heartbeat options for a share group member.
    #[must_use]
    pub fn new(group_id: impl Into<String>, member_id: impl Into<String>) -> Self {
        Self {
            group_id: group_id.into(),
            member_id: member_id.into(),
            member_epoch: 0,
            rack_id: None,
            subscribed_topic_names: None,
        }
    }
}

/// Heartbeat assignment returned by consumer/share group heartbeats.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HeartbeatAssignment {
    /// Assigned topic partitions.
    pub topic_partitions: Vec<HeartbeatTopicPartitions>,
}

/// Backwards-friendly alias for share heartbeat assignments.
#[allow(dead_code)]
pub type ShareAssignment = HeartbeatAssignment;

/// Parsed response from a low-level consumer/share group heartbeat.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareHeartbeatResponseData {
    /// Quota throttle time in milliseconds.
    pub throttle_time_ms: i32,
    /// Top-level broker error code.
    pub error_code: i16,
    /// Optional top-level error message.
    pub error_message: Option<String>,
    /// Member ID assigned by the coordinator.
    pub member_id: Option<String>,
    /// Member epoch assigned by the coordinator.
    pub member_epoch: i32,
    /// Heartbeat interval in milliseconds.
    pub heartbeat_interval_ms: i32,
    /// Optional assignment.
    pub assignment: Option<HeartbeatAssignment>,
}

/// Parsed response from `ConsumerGroupHeartbeat`.
pub type ConsumerGroupHeartbeatResponseData = ShareHeartbeatResponseData;

/// Parsed response from `ShareGroupHeartbeat`.
pub type ShareGroupHeartbeatResponseData = ShareHeartbeatResponseData;

/// One share acknowledgement batch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgementBatch {
    /// First offset in the batch.
    pub first_offset: i64,
    /// Last offset in the batch, inclusive.
    pub last_offset: i64,
    /// One Kafka share acknowledgement type code per acknowledged record.
    pub acknowledge_types: Vec<i8>,
}

impl ShareAcknowledgementBatch {
    /// Create an acknowledgement batch.
    #[must_use]
    pub fn new<I>(first_offset: i64, last_offset: i64, acknowledge_types: I) -> Self
    where
        I: IntoIterator<Item = i8>,
    {
        Self {
            first_offset,
            last_offset,
            acknowledge_types: acknowledge_types.into_iter().collect(),
        }
    }
}

/// One partition in a `ShareFetch` request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareFetchPartition {
    /// Partition index.
    pub partition_index: i32,
    /// Acknowledgement batches to send with this fetch.
    pub acknowledgement_batches: Vec<ShareAcknowledgementBatch>,
}

impl ShareFetchPartition {
    /// Create a share fetch partition.
    #[must_use]
    pub fn new<I>(partition_index: i32, acknowledgement_batches: I) -> Self
    where
        I: IntoIterator<Item = ShareAcknowledgementBatch>,
    {
        Self {
            partition_index,
            acknowledgement_batches: acknowledgement_batches.into_iter().collect(),
        }
    }
}

/// One topic in a `ShareFetch` request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareFetchTopic {
    /// Topic UUID.
    pub topic_id: Uuid,
    /// Partitions to fetch from or acknowledge.
    pub partitions: Vec<ShareFetchPartition>,
}

impl ShareFetchTopic {
    /// Create a share fetch topic.
    #[must_use]
    pub fn new<I>(topic_id: Uuid, partitions: I) -> Self
    where
        I: IntoIterator<Item = ShareFetchPartition>,
    {
        Self {
            topic_id,
            partitions: partitions.into_iter().collect(),
        }
    }
}

/// One forgotten topic entry in a `ShareFetch` request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForgottenShareFetchTopic {
    /// Topic UUID.
    pub topic_id: Uuid,
    /// Partition indexes to remove from the share session.
    pub partitions: Vec<i32>,
}

impl ForgottenShareFetchTopic {
    /// Create a forgotten share topic entry.
    #[must_use]
    pub fn new<I>(topic_id: Uuid, partitions: I) -> Self
    where
        I: IntoIterator<Item = i32>,
    {
        Self {
            topic_id,
            partitions: partitions.into_iter().collect(),
        }
    }
}

/// Options for `ShareFetch`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareFetchOptions {
    /// Share group ID.
    pub group_id: Option<String>,
    /// Share group member ID.
    pub member_id: Option<String>,
    /// Current share session epoch.
    pub share_session_epoch: i32,
    /// Maximum wait in milliseconds.
    pub max_wait_ms: i32,
    /// Minimum response bytes.
    pub min_bytes: i32,
    /// Maximum response bytes.
    pub max_bytes: i32,
    /// Maximum records to fetch.
    pub max_records: i32,
    /// Optimal acquired-record/acknowledgement batch size.
    pub batch_size: i32,
    /// Topics to fetch from.
    pub topics: Vec<ShareFetchTopic>,
    /// Topics to remove from this share session.
    pub forgotten_topics_data: Vec<ForgottenShareFetchTopic>,
}

impl ShareFetchOptions {
    /// Create a share fetch request.
    #[must_use]
    pub fn new(group_id: impl Into<String>, member_id: impl Into<String>) -> Self {
        Self {
            group_id: Some(group_id.into()),
            member_id: Some(member_id.into()),
            share_session_epoch: 0,
            max_wait_ms: 500,
            min_bytes: 1,
            max_bytes: 50 * 1024 * 1024,
            max_records: 500,
            batch_size: 1,
            topics: Vec::new(),
            forgotten_topics_data: Vec::new(),
        }
    }

    /// Set topics to fetch.
    #[must_use]
    pub fn with_topics<I>(mut self, topics: I) -> Self
    where
        I: IntoIterator<Item = ShareFetchTopic>,
    {
        self.topics = topics.into_iter().collect();
        self
    }

    /// Set topics to remove from the share session.
    #[must_use]
    pub fn with_forgotten_topics_data<I>(mut self, topics: I) -> Self
    where
        I: IntoIterator<Item = ForgottenShareFetchTopic>,
    {
        self.forgotten_topics_data = topics.into_iter().collect();
        self
    }
}

/// One partition in a `ShareAcknowledge` request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgePartition {
    /// Partition index.
    pub partition_index: i32,
    /// Acknowledgement batches.
    pub acknowledgement_batches: Vec<ShareAcknowledgementBatch>,
}

impl ShareAcknowledgePartition {
    /// Create a share acknowledgement partition.
    #[must_use]
    pub fn new<I>(partition_index: i32, acknowledgement_batches: I) -> Self
    where
        I: IntoIterator<Item = ShareAcknowledgementBatch>,
    {
        Self {
            partition_index,
            acknowledgement_batches: acknowledgement_batches.into_iter().collect(),
        }
    }
}

/// One topic in a `ShareAcknowledge` request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgeTopic {
    /// Topic UUID.
    pub topic_id: Uuid,
    /// Partitions containing records to acknowledge.
    pub partitions: Vec<ShareAcknowledgePartition>,
}

impl ShareAcknowledgeTopic {
    /// Create a share acknowledgement topic.
    #[must_use]
    pub fn new<I>(topic_id: Uuid, partitions: I) -> Self
    where
        I: IntoIterator<Item = ShareAcknowledgePartition>,
    {
        Self {
            topic_id,
            partitions: partitions.into_iter().collect(),
        }
    }
}

impl From<ShareFetchTopic> for ShareAcknowledgeTopic {
    fn from(topic: ShareFetchTopic) -> Self {
        Self {
            topic_id: topic.topic_id,
            partitions: topic
                .partitions
                .into_iter()
                .map(|partition| ShareAcknowledgePartition {
                    partition_index: partition.partition_index,
                    acknowledgement_batches: partition.acknowledgement_batches,
                })
                .collect(),
        }
    }
}

/// Options for `ShareAcknowledge`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgeOptions {
    /// Share group ID.
    pub group_id: Option<String>,
    /// Share group member ID.
    pub member_id: Option<String>,
    /// Current share session epoch.
    pub share_session_epoch: i32,
    /// Topics containing acknowledgements.
    pub topics: Vec<ShareAcknowledgeTopic>,
}

impl ShareAcknowledgeOptions {
    /// Create a share acknowledgement request.
    #[must_use]
    pub fn new(group_id: impl Into<String>, member_id: impl Into<String>) -> Self {
        Self {
            group_id: Some(group_id.into()),
            member_id: Some(member_id.into()),
            share_session_epoch: 0,
            topics: Vec::new(),
        }
    }

    /// Set topics to acknowledge.
    #[must_use]
    pub fn with_topics<I, T>(mut self, topics: I) -> Self
    where
        I: IntoIterator<Item = T>,
        T: Into<ShareAcknowledgeTopic>,
    {
        self.topics = topics.into_iter().map(Into::into).collect();
        self
    }
}

/// Current leader reference returned in share responses.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ShareLeader {
    /// Current leader broker ID.
    pub leader_id: i32,
    /// Current leader epoch.
    pub leader_epoch: i32,
}

/// Broker endpoint returned in share responses.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareNodeEndpoint {
    /// Broker ID.
    pub node_id: i32,
    /// Broker host.
    pub host: String,
    /// Broker port.
    pub port: i32,
    /// Optional broker rack.
    pub rack: Option<String>,
}

/// Acquired record range returned by `ShareFetch`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcquiredRecords {
    /// First acquired offset.
    pub first_offset: i64,
    /// Last acquired offset.
    pub last_offset: i64,
    /// Delivery count for this range.
    pub delivery_count: i16,
}

/// One partition in a `ShareFetch` response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareFetchPartitionResponse {
    /// Partition index.
    pub partition_index: i32,
    /// Fetch error code.
    pub error_code: i16,
    /// Optional fetch error message.
    pub error_message: Option<String>,
    /// Acknowledge error code.
    pub acknowledge_error_code: i16,
    /// Optional acknowledge error message.
    pub acknowledge_error_message: Option<String>,
    /// Current leader.
    pub current_leader: ShareLeader,
    /// Raw record batch bytes.
    pub records: Option<Bytes>,
    /// Acquired record ranges.
    pub acquired_records: Vec<ShareAcquiredRecords>,
}

/// One topic in a `ShareFetch` response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareFetchTopicResponse {
    /// Topic UUID.
    pub topic_id: Uuid,
    /// Partition responses.
    pub partitions: Vec<ShareFetchPartitionResponse>,
}

/// Parsed response from `ShareFetch`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareFetchResponseData {
    /// Quota throttle time in milliseconds.
    pub throttle_time_ms: i32,
    /// Top-level response error code.
    pub error_code: i16,
    /// Optional top-level error message.
    pub error_message: Option<String>,
    /// Acquisition lock timeout in milliseconds.
    pub acquisition_lock_timeout_ms: i32,
    /// Topic responses.
    pub responses: Vec<ShareFetchTopicResponse>,
    /// Current leader endpoints.
    pub node_endpoints: Vec<ShareNodeEndpoint>,
}

/// One partition in a `ShareAcknowledge` response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgePartitionResponse {
    /// Partition index.
    pub partition_index: i32,
    /// Error code.
    pub error_code: i16,
    /// Optional error message.
    pub error_message: Option<String>,
    /// Current leader.
    pub current_leader: ShareLeader,
}

/// One topic in a `ShareAcknowledge` response.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgeTopicResponse {
    /// Topic UUID.
    pub topic_id: Uuid,
    /// Partition responses.
    pub partitions: Vec<ShareAcknowledgePartitionResponse>,
}

/// Backwards-friendly alias for one `ShareAcknowledge` topic response.
#[allow(dead_code)]
pub type ShareAcknowledgeTopicResponseData = ShareAcknowledgeTopicResponse;

/// Parsed response from `ShareAcknowledge`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ShareAcknowledgeResponseData {
    /// Quota throttle time in milliseconds.
    pub throttle_time_ms: i32,
    /// Top-level response error code.
    pub error_code: i16,
    /// Optional top-level error message.
    pub error_message: Option<String>,
    /// Topic responses.
    pub responses: Vec<ShareAcknowledgeTopicResponse>,
    /// Current leader endpoints.
    pub node_endpoints: Vec<ShareNodeEndpoint>,
}

/// Build a `ConsumerGroupHeartbeat` request.
pub fn build_consumer_group_heartbeat_request(
    correlation_id: i32,
    client_id: &str,
    options: &ConsumerGroupHeartbeatOptions,
) -> (RequestHeader, ConsumerGroupHeartbeatRequest) {
    let header = request_header(
        correlation_id,
        client_id,
        ApiKey::ConsumerGroupHeartbeat,
        API_VERSION_CONSUMER_GROUP_HEARTBEAT,
    );
    let request = ConsumerGroupHeartbeatRequest::default()
        .with_group_id(group_id(options.group_id.clone()))
        .with_member_id(str_bytes(options.member_id.clone()))
        .with_member_epoch(options.member_epoch)
        .with_instance_id(optional_str_bytes(options.instance_id.clone()))
        .with_rack_id(optional_str_bytes(options.rack_id.clone()))
        .with_rebalance_timeout_ms(options.rebalance_timeout_ms)
        .with_subscribed_topic_names(optional_topic_names(options.subscribed_topic_names.clone()))
        .with_subscribed_topic_regex(optional_str_bytes(options.subscribed_topic_regex.clone()))
        .with_server_assignor(optional_str_bytes(options.server_assignor.clone()))
        .with_topic_partitions(
            options
                .topic_partitions
                .as_deref()
                .map(to_consumer_request_topic_partitions),
        );

    (header, request)
}

/// Build a `ShareGroupHeartbeat` request.
pub fn build_share_group_heartbeat_request(
    correlation_id: i32,
    client_id: &str,
    options: &ShareGroupHeartbeatOptions,
) -> (RequestHeader, ShareGroupHeartbeatRequest) {
    let header = request_header(
        correlation_id,
        client_id,
        ApiKey::ShareGroupHeartbeat,
        API_VERSION_SHARE_GROUP_HEARTBEAT,
    );
    let request = ShareGroupHeartbeatRequest::default()
        .with_group_id(group_id(options.group_id.clone()))
        .with_member_id(str_bytes(options.member_id.clone()))
        .with_member_epoch(options.member_epoch)
        .with_rack_id(optional_str_bytes(options.rack_id.clone()))
        .with_subscribed_topic_names(optional_topic_names(options.subscribed_topic_names.clone()));

    (header, request)
}

/// Build a `ShareFetch` request.
pub fn build_share_fetch_request(
    correlation_id: i32,
    client_id: &str,
    options: &ShareFetchOptions,
) -> (RequestHeader, ShareFetchRequest) {
    let header = request_header(
        correlation_id,
        client_id,
        ApiKey::ShareFetch,
        API_VERSION_SHARE_FETCH,
    );
    let request = ShareFetchRequest::default()
        .with_group_id(optional_group_id(options.group_id.clone()))
        .with_member_id(optional_str_bytes(options.member_id.clone()))
        .with_share_session_epoch(options.share_session_epoch)
        .with_max_wait_ms(options.max_wait_ms)
        .with_min_bytes(options.min_bytes)
        .with_max_bytes(options.max_bytes)
        .with_max_records(options.max_records)
        .with_batch_size(options.batch_size)
        .with_topics(to_share_fetch_topics(&options.topics))
        .with_forgotten_topics_data(to_forgotten_share_fetch_topics(
            &options.forgotten_topics_data,
        ));

    (header, request)
}

/// Build a `ShareAcknowledge` request.
pub fn build_share_acknowledge_request(
    correlation_id: i32,
    client_id: &str,
    options: &ShareAcknowledgeOptions,
) -> (RequestHeader, ShareAcknowledgeRequest) {
    let header = request_header(
        correlation_id,
        client_id,
        ApiKey::ShareAcknowledge,
        API_VERSION_SHARE_ACKNOWLEDGE,
    );
    let request = ShareAcknowledgeRequest::default()
        .with_group_id(optional_group_id(options.group_id.clone()))
        .with_member_id(optional_str_bytes(options.member_id.clone()))
        .with_share_session_epoch(options.share_session_epoch)
        .with_topics(to_share_acknowledge_topics(&options.topics));

    (header, request)
}

/// Convert a generated `ConsumerGroupHeartbeatResponse`.
#[must_use]
pub fn convert_consumer_group_heartbeat_response(
    response: ConsumerGroupHeartbeatResponse,
) -> ConsumerGroupHeartbeatResponseData {
    ConsumerGroupHeartbeatResponseData {
        throttle_time_ms: response.throttle_time_ms,
        error_code: response.error_code,
        error_message: optional_string(response.error_message),
        member_id: optional_string(response.member_id),
        member_epoch: response.member_epoch,
        heartbeat_interval_ms: response.heartbeat_interval_ms,
        assignment: response.assignment.map(convert_consumer_assignment),
    }
}

/// Convert a generated `ShareGroupHeartbeatResponse`.
#[must_use]
pub fn convert_share_group_heartbeat_response(
    response: ShareGroupHeartbeatResponse,
) -> ShareGroupHeartbeatResponseData {
    ShareGroupHeartbeatResponseData {
        throttle_time_ms: response.throttle_time_ms,
        error_code: response.error_code,
        error_message: optional_string(response.error_message),
        member_id: optional_string(response.member_id),
        member_epoch: response.member_epoch,
        heartbeat_interval_ms: response.heartbeat_interval_ms,
        assignment: response.assignment.map(convert_share_assignment),
    }
}

/// Convert a generated `ShareFetchResponse`.
#[must_use]
pub fn convert_share_fetch_response(response: ShareFetchResponse) -> ShareFetchResponseData {
    ShareFetchResponseData {
        throttle_time_ms: response.throttle_time_ms,
        error_code: response.error_code,
        error_message: optional_string(response.error_message),
        acquisition_lock_timeout_ms: response.acquisition_lock_timeout_ms,
        responses: response
            .responses
            .into_iter()
            .map(|topic| ShareFetchTopicResponse {
                topic_id: topic.topic_id,
                partitions: topic
                    .partitions
                    .into_iter()
                    .map(convert_share_fetch_partition_response)
                    .collect(),
            })
            .collect(),
        node_endpoints: response
            .node_endpoints
            .into_iter()
            .map(convert_share_fetch_node_endpoint)
            .collect(),
    }
}

/// Convert a generated `ShareAcknowledgeResponse`.
#[must_use]
pub fn convert_share_acknowledge_response(
    response: ShareAcknowledgeResponse,
) -> ShareAcknowledgeResponseData {
    ShareAcknowledgeResponseData {
        throttle_time_ms: response.throttle_time_ms,
        error_code: response.error_code,
        error_message: optional_string(response.error_message),
        responses: response
            .responses
            .into_iter()
            .map(|topic| ShareAcknowledgeTopicResponse {
                topic_id: topic.topic_id,
                partitions: topic
                    .partitions
                    .into_iter()
                    .map(convert_share_acknowledge_partition_response)
                    .collect(),
            })
            .collect(),
        node_endpoints: response
            .node_endpoints
            .into_iter()
            .map(convert_share_acknowledge_node_endpoint)
            .collect(),
    }
}

fn request_header(
    correlation_id: i32,
    client_id: &str,
    api_key: ApiKey,
    api_version: i16,
) -> RequestHeader {
    RequestHeader::default()
        .with_client_id(Some(str_bytes(client_id.to_owned())))
        .with_request_api_key(api_key as i16)
        .with_request_api_version(api_version)
        .with_correlation_id(correlation_id)
}

fn str_bytes(value: String) -> StrBytes {
    StrBytes::from_string(value)
}

fn group_id(value: String) -> GroupId {
    GroupId(str_bytes(value))
}

fn optional_group_id(value: Option<String>) -> Option<GroupId> {
    value.map(group_id)
}

fn optional_str_bytes(value: Option<String>) -> Option<StrBytes> {
    value.map(str_bytes)
}

fn optional_string(value: Option<StrBytes>) -> Option<String> {
    value.map(|value| value.to_string())
}

fn optional_topic_names(values: Option<Vec<String>>) -> Option<Vec<TopicName>> {
    values.map(|items| {
        items
            .into_iter()
            .map(|topic| TopicName(str_bytes(topic)))
            .collect()
    })
}

fn to_consumer_request_topic_partitions(
    topics: &[HeartbeatTopicPartitions],
) -> Vec<cgh_req::TopicPartitions> {
    topics
        .iter()
        .map(|topic| {
            cgh_req::TopicPartitions::default()
                .with_topic_id(topic.topic_id)
                .with_partitions(topic.partitions.clone())
        })
        .collect()
}

fn convert_consumer_assignment(assignment: cgh_resp::Assignment) -> HeartbeatAssignment {
    HeartbeatAssignment {
        topic_partitions: assignment
            .topic_partitions
            .into_iter()
            .map(|topic| HeartbeatTopicPartitions {
                topic_id: topic.topic_id,
                partitions: topic.partitions,
            })
            .collect(),
    }
}

fn convert_share_assignment(assignment: sgh_resp::Assignment) -> HeartbeatAssignment {
    HeartbeatAssignment {
        topic_partitions: assignment
            .topic_partitions
            .into_iter()
            .map(|topic| HeartbeatTopicPartitions {
                topic_id: topic.topic_id,
                partitions: topic.partitions,
            })
            .collect(),
    }
}

fn to_share_acknowledgement_batch(
    batch: &ShareAcknowledgementBatch,
) -> sf_req::AcknowledgementBatch {
    sf_req::AcknowledgementBatch::default()
        .with_first_offset(batch.first_offset)
        .with_last_offset(batch.last_offset)
        .with_acknowledge_types(batch.acknowledge_types.clone())
}

fn to_share_fetch_topics(topics: &[ShareFetchTopic]) -> Vec<sf_req::FetchTopic> {
    topics
        .iter()
        .map(|topic| {
            sf_req::FetchTopic::default()
                .with_topic_id(topic.topic_id)
                .with_partitions(
                    topic
                        .partitions
                        .iter()
                        .map(|partition| {
                            sf_req::FetchPartition::default()
                                .with_partition_index(partition.partition_index)
                                .with_acknowledgement_batches(
                                    partition
                                        .acknowledgement_batches
                                        .iter()
                                        .map(to_share_acknowledgement_batch)
                                        .collect(),
                                )
                        })
                        .collect(),
                )
        })
        .collect()
}

fn to_forgotten_share_fetch_topics(
    topics: &[ForgottenShareFetchTopic],
) -> Vec<sf_req::ForgottenTopic> {
    topics
        .iter()
        .map(|topic| {
            sf_req::ForgottenTopic::default()
                .with_topic_id(topic.topic_id)
                .with_partitions(topic.partitions.clone())
        })
        .collect()
}

fn to_share_acknowledgement_batch_request(
    batch: &ShareAcknowledgementBatch,
) -> sa_req::AcknowledgementBatch {
    sa_req::AcknowledgementBatch::default()
        .with_first_offset(batch.first_offset)
        .with_last_offset(batch.last_offset)
        .with_acknowledge_types(batch.acknowledge_types.clone())
}

fn to_share_acknowledge_topics(topics: &[ShareAcknowledgeTopic]) -> Vec<sa_req::AcknowledgeTopic> {
    topics
        .iter()
        .map(|topic| {
            sa_req::AcknowledgeTopic::default()
                .with_topic_id(topic.topic_id)
                .with_partitions(
                    topic
                        .partitions
                        .iter()
                        .map(|partition| {
                            sa_req::AcknowledgePartition::default()
                                .with_partition_index(partition.partition_index)
                                .with_acknowledgement_batches(
                                    partition
                                        .acknowledgement_batches
                                        .iter()
                                        .map(to_share_acknowledgement_batch_request)
                                        .collect(),
                                )
                        })
                        .collect(),
                )
        })
        .collect()
}

fn convert_share_fetch_partition_response(
    partition: sf_resp::PartitionData,
) -> ShareFetchPartitionResponse {
    ShareFetchPartitionResponse {
        partition_index: partition.partition_index,
        error_code: partition.error_code,
        error_message: optional_string(partition.error_message),
        acknowledge_error_code: partition.acknowledge_error_code,
        acknowledge_error_message: optional_string(partition.acknowledge_error_message),
        current_leader: ShareLeader {
            leader_id: partition.current_leader.leader_id,
            leader_epoch: partition.current_leader.leader_epoch,
        },
        records: partition.records,
        acquired_records: partition
            .acquired_records
            .into_iter()
            .map(|records| ShareAcquiredRecords {
                first_offset: records.first_offset,
                last_offset: records.last_offset,
                delivery_count: records.delivery_count,
            })
            .collect(),
    }
}

fn convert_share_fetch_node_endpoint(endpoint: sf_resp::NodeEndpoint) -> ShareNodeEndpoint {
    ShareNodeEndpoint {
        node_id: *endpoint.node_id,
        host: endpoint.host.to_string(),
        port: endpoint.port,
        rack: optional_string(endpoint.rack),
    }
}

fn convert_share_acknowledge_partition_response(
    partition: sa_resp::PartitionData,
) -> ShareAcknowledgePartitionResponse {
    ShareAcknowledgePartitionResponse {
        partition_index: partition.partition_index,
        error_code: partition.error_code,
        error_message: optional_string(partition.error_message),
        current_leader: ShareLeader {
            leader_id: partition.current_leader.leader_id,
            leader_epoch: partition.current_leader.leader_epoch,
        },
    }
}

fn convert_share_acknowledge_node_endpoint(endpoint: sa_resp::NodeEndpoint) -> ShareNodeEndpoint {
    ShareNodeEndpoint {
        node_id: *endpoint.node_id,
        host: endpoint.host.to_string(),
        port: endpoint.port,
        rack: optional_string(endpoint.rack),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use kafka_protocol::messages::BrokerId;

    #[test]
    fn consumer_group_heartbeat_request_maps_all_optional_fields() {
        let topic_id = Uuid::from_u128(1);
        let mut options = ConsumerGroupHeartbeatOptions::new("group-a", "member-a");
        options.member_epoch = 3;
        options.instance_id = Some("instance-a".to_owned());
        options.rack_id = Some("rack-a".to_owned());
        options.rebalance_timeout_ms = 45_000;
        options.subscribed_topic_names = Some(vec!["topic-a".to_owned(), "topic-b".to_owned()]);
        options.subscribed_topic_regex = Some("topic-.*".to_owned());
        options.server_assignor = Some("range".to_owned());
        options.topic_partitions = Some(vec![HeartbeatTopicPartitions::new(topic_id, [0, 2])]);

        let (header, request) = build_consumer_group_heartbeat_request(11, "client-a", &options);

        assert_eq!(
            header.request_api_key,
            ApiKey::ConsumerGroupHeartbeat as i16
        );
        assert_eq!(
            header.request_api_version,
            API_VERSION_CONSUMER_GROUP_HEARTBEAT
        );
        assert_eq!(header.correlation_id, 11);
        assert_eq!(request.group_id.0.to_string(), "group-a");
        assert_eq!(request.member_id.to_string(), "member-a");
        assert_eq!(request.member_epoch, 3);
        assert_eq!(
            request
                .instance_id
                .as_ref()
                .map(ToString::to_string)
                .as_deref(),
            Some("instance-a")
        );
        assert_eq!(
            request.rack_id.as_ref().map(ToString::to_string).as_deref(),
            Some("rack-a")
        );
        assert_eq!(request.rebalance_timeout_ms, 45_000);
        assert_eq!(
            request
                .subscribed_topic_names
                .as_ref()
                .unwrap()
                .iter()
                .map(|topic| topic.0.to_string())
                .collect::<Vec<_>>(),
            vec!["topic-a".to_owned(), "topic-b".to_owned()]
        );
        assert_eq!(
            request
                .subscribed_topic_regex
                .as_ref()
                .map(ToString::to_string)
                .as_deref(),
            Some("topic-.*")
        );
        assert_eq!(
            request
                .server_assignor
                .as_ref()
                .map(ToString::to_string)
                .as_deref(),
            Some("range")
        );
        let partitions = request.topic_partitions.as_ref().unwrap();
        assert_eq!(partitions[0].topic_id, topic_id);
        assert_eq!(partitions[0].partitions, vec![0, 2]);
    }

    #[test]
    fn share_group_heartbeat_request_maps_topics() {
        let mut options = ShareGroupHeartbeatOptions::new("share-a", "member-b");
        options.member_epoch = -1;
        options.rack_id = Some("rack-b".to_owned());
        options.subscribed_topic_names = Some(vec!["topic-a".to_owned()]);

        let (header, request) = build_share_group_heartbeat_request(12, "client-b", &options);

        assert_eq!(header.request_api_key, ApiKey::ShareGroupHeartbeat as i16);
        assert_eq!(
            header.request_api_version,
            API_VERSION_SHARE_GROUP_HEARTBEAT
        );
        assert_eq!(request.group_id.0.to_string(), "share-a");
        assert_eq!(request.member_id.to_string(), "member-b");
        assert_eq!(request.member_epoch, -1);
        assert_eq!(
            request.rack_id.as_ref().map(ToString::to_string).as_deref(),
            Some("rack-b")
        );
        assert_eq!(
            request
                .subscribed_topic_names
                .as_ref()
                .unwrap()
                .iter()
                .map(|topic| topic.0.to_string())
                .collect::<Vec<_>>(),
            vec!["topic-a".to_owned()]
        );
    }

    #[test]
    fn share_fetch_request_maps_topics_and_acknowledgements() {
        let topic_id = Uuid::from_u128(2);
        let forgotten_topic_id = Uuid::from_u128(3);
        let mut options = ShareFetchOptions::new("share-a", "member-a");
        options.share_session_epoch = 4;
        options.max_wait_ms = 1_000;
        options.min_bytes = 2;
        options.max_bytes = 4_096;
        options.max_records = 10;
        options.batch_size = 5;
        options.topics = vec![ShareFetchTopic::new(
            topic_id,
            [ShareFetchPartition::new(
                7,
                [ShareAcknowledgementBatch::new(
                    12,
                    14,
                    [SHARE_ACK_TYPE_ACCEPT, SHARE_ACK_TYPE_RELEASE],
                )],
            )],
        )];
        options.forgotten_topics_data =
            vec![ForgottenShareFetchTopic::new(forgotten_topic_id, [9])];

        let (header, request) = build_share_fetch_request(13, "client-c", &options);

        assert_eq!(header.request_api_key, ApiKey::ShareFetch as i16);
        assert_eq!(header.request_api_version, API_VERSION_SHARE_FETCH);
        assert_eq!(request.share_session_epoch, 4);
        assert_eq!(request.max_wait_ms, 1_000);
        assert_eq!(request.min_bytes, 2);
        assert_eq!(request.max_bytes, 4_096);
        assert_eq!(request.max_records, 10);
        assert_eq!(request.batch_size, 5);
        assert_eq!(request.topics[0].topic_id, topic_id);
        assert_eq!(request.topics[0].partitions[0].partition_index, 7);
        assert_eq!(
            request.topics[0].partitions[0].acknowledgement_batches[0].acknowledge_types,
            vec![SHARE_ACK_TYPE_ACCEPT, SHARE_ACK_TYPE_RELEASE]
        );
        assert_eq!(
            request.forgotten_topics_data[0].topic_id,
            forgotten_topic_id
        );
        assert_eq!(request.forgotten_topics_data[0].partitions, vec![9]);
    }

    #[test]
    fn share_acknowledge_request_maps_topics_and_batches() {
        let topic_id = Uuid::from_u128(4);
        let mut options = ShareAcknowledgeOptions::new("share-a", "member-a").with_topics([
            ShareAcknowledgeTopic::new(
                topic_id,
                [ShareAcknowledgePartition::new(
                    1,
                    [ShareAcknowledgementBatch::new(
                        2,
                        3,
                        [SHARE_ACK_TYPE_REJECT],
                    )],
                )],
            ),
        ]);
        options.share_session_epoch = 8;

        let (header, request) = build_share_acknowledge_request(14, "client-d", &options);

        assert_eq!(header.request_api_key, ApiKey::ShareAcknowledge as i16);
        assert_eq!(header.request_api_version, API_VERSION_SHARE_ACKNOWLEDGE);
        assert_eq!(request.share_session_epoch, 8);
        assert_eq!(request.topics[0].topic_id, topic_id);
        assert_eq!(request.topics[0].partitions[0].partition_index, 1);
        assert_eq!(
            request.topics[0].partitions[0].acknowledgement_batches[0].acknowledge_types,
            vec![SHARE_ACK_TYPE_REJECT]
        );
    }

    #[test]
    fn consumer_group_heartbeat_response_maps_assignment() {
        let topic_id = Uuid::from_u128(5);
        let response = ConsumerGroupHeartbeatResponse::default()
            .with_throttle_time_ms(10)
            .with_error_code(0)
            .with_error_message(Some(str_bytes("ok".to_owned())))
            .with_member_id(Some(str_bytes("member-a".to_owned())))
            .with_member_epoch(6)
            .with_heartbeat_interval_ms(3_000)
            .with_assignment(Some(cgh_resp::Assignment::default().with_topic_partitions(
                vec![
                cgh_resp::TopicPartitions::default()
                    .with_topic_id(topic_id)
                    .with_partitions(vec![0, 1]),
            ],
            )));

        let converted = convert_consumer_group_heartbeat_response(response);

        assert_eq!(converted.throttle_time_ms, 10);
        assert_eq!(converted.error_message.as_deref(), Some("ok"));
        assert_eq!(converted.member_id.as_deref(), Some("member-a"));
        assert_eq!(converted.member_epoch, 6);
        assert_eq!(converted.heartbeat_interval_ms, 3_000);
        assert_eq!(
            converted.assignment.unwrap().topic_partitions,
            vec![HeartbeatTopicPartitions::new(topic_id, [0, 1])]
        );
    }

    #[test]
    fn share_fetch_response_maps_records_and_endpoints() {
        let topic_id = Uuid::from_u128(6);
        let response = ShareFetchResponse::default()
            .with_throttle_time_ms(7)
            .with_error_code(1)
            .with_error_message(Some(str_bytes("top-error".to_owned())))
            .with_acquisition_lock_timeout_ms(30_000)
            .with_responses(vec![
                sf_resp::ShareFetchableTopicResponse::default()
                    .with_topic_id(topic_id)
                    .with_partitions(vec![
                        sf_resp::PartitionData::default()
                            .with_partition_index(3)
                            .with_error_code(4)
                            .with_error_message(Some(str_bytes("fetch-error".to_owned())))
                            .with_acknowledge_error_code(5)
                            .with_acknowledge_error_message(Some(str_bytes("ack-error".to_owned())))
                            .with_current_leader(
                                sf_resp::LeaderIdAndEpoch::default()
                                    .with_leader_id(9)
                                    .with_leader_epoch(2),
                            )
                            .with_records(Some(Bytes::from_static(b"records")))
                            .with_acquired_records(vec![
                                sf_resp::AcquiredRecords::default()
                                    .with_first_offset(11)
                                    .with_last_offset(12)
                                    .with_delivery_count(2),
                            ]),
                    ]),
            ])
            .with_node_endpoints(vec![
                sf_resp::NodeEndpoint::default()
                    .with_node_id(BrokerId(9))
                    .with_host(str_bytes("broker".to_owned()))
                    .with_port(9092)
                    .with_rack(Some(str_bytes("rack".to_owned()))),
            ]);

        let converted = convert_share_fetch_response(response);

        assert_eq!(converted.throttle_time_ms, 7);
        assert_eq!(converted.error_message.as_deref(), Some("top-error"));
        assert_eq!(converted.acquisition_lock_timeout_ms, 30_000);
        assert_eq!(converted.responses[0].topic_id, topic_id);
        let partition = &converted.responses[0].partitions[0];
        assert_eq!(partition.partition_index, 3);
        assert_eq!(partition.error_message.as_deref(), Some("fetch-error"));
        assert_eq!(
            partition.acknowledge_error_message.as_deref(),
            Some("ack-error")
        );
        assert_eq!(
            partition.current_leader,
            ShareLeader {
                leader_id: 9,
                leader_epoch: 2,
            }
        );
        assert_eq!(partition.records, Some(Bytes::from_static(b"records")));
        assert_eq!(
            partition.acquired_records,
            vec![ShareAcquiredRecords {
                first_offset: 11,
                last_offset: 12,
                delivery_count: 2,
            }]
        );
        assert_eq!(
            converted.node_endpoints,
            vec![ShareNodeEndpoint {
                node_id: 9,
                host: "broker".to_owned(),
                port: 9092,
                rack: Some("rack".to_owned()),
            }]
        );
    }

    #[test]
    fn share_acknowledge_response_maps_partitions_and_endpoints() {
        let topic_id = Uuid::from_u128(7);
        let response = ShareAcknowledgeResponse::default()
            .with_throttle_time_ms(2)
            .with_error_code(3)
            .with_error_message(Some(str_bytes("top".to_owned())))
            .with_responses(vec![
                sa_resp::ShareAcknowledgeTopicResponse::default()
                    .with_topic_id(topic_id)
                    .with_partitions(vec![
                        sa_resp::PartitionData::default()
                            .with_partition_index(4)
                            .with_error_code(5)
                            .with_error_message(Some(str_bytes("partition".to_owned())))
                            .with_current_leader(
                                sa_resp::LeaderIdAndEpoch::default()
                                    .with_leader_id(6)
                                    .with_leader_epoch(7),
                            ),
                    ]),
            ])
            .with_node_endpoints(vec![
                sa_resp::NodeEndpoint::default()
                    .with_node_id(BrokerId(6))
                    .with_host(str_bytes("broker-a".to_owned()))
                    .with_port(9093),
            ]);

        let converted = convert_share_acknowledge_response(response);

        assert_eq!(converted.throttle_time_ms, 2);
        assert_eq!(converted.error_code, 3);
        assert_eq!(converted.error_message.as_deref(), Some("top"));
        assert_eq!(converted.responses[0].topic_id, topic_id);
        assert_eq!(
            converted.responses[0].partitions[0],
            ShareAcknowledgePartitionResponse {
                partition_index: 4,
                error_code: 5,
                error_message: Some("partition".to_owned()),
                current_leader: ShareLeader {
                    leader_id: 6,
                    leader_epoch: 7,
                },
            }
        );
        assert_eq!(
            converted.node_endpoints,
            vec![ShareNodeEndpoint {
                node_id: 6,
                host: "broker-a".to_owned(),
                port: 9093,
                rack: None,
            }]
        );
    }
}
