//! Raw generated Kafka protocol request support.

use kafka_protocol::messages::RequestHeader;
use kafka_protocol::protocol::StrBytes;

use super::{KafkaClient, transport};
use crate::error::{Error, Result};

impl KafkaClient {
    /// Sends a typed low-level `kafka-protocol` request and returns its raw generated response.
    ///
    /// This is intended for advanced users who need protocol coverage beyond
    /// the stable high-level [`KafkaClient`] methods, including broker,
    /// controller, coordinator, or raft-internal APIs generated by
    /// `kafka-protocol`. Callers are responsible for choosing a valid `api_key`,
    /// `api_version`, and request/response type pair.
    ///
    /// # Errors
    ///
    /// Returns an error if brokers are unreachable, the request cannot be
    /// encoded, the response cannot be decoded, or the selected API/version is
    /// not accepted by the broker.
    pub fn send_raw_protocol_request<Req, Resp>(
        &mut self,
        api_key: i16,
        api_version: i16,
        request: &Req,
    ) -> Result<Resp>
    where
        Req: kafka_protocol::protocol::Encodable + kafka_protocol::protocol::HeaderVersion,
        Resp: kafka_protocol::protocol::Decodable + kafka_protocol::protocol::HeaderVersion,
    {
        let correlation_id = self.state.next_correlation_id();
        let now = std::time::Instant::now();
        let hosts = self.config.hosts.clone();
        let mut last_err: Option<Error> = None;

        for host in hosts {
            let conn = match self.conn_pool.get_conn(&host, now) {
                Ok(conn) => conn,
                Err(e) => {
                    last_err = Some(e.with_broker_context(&host, "RawProtocolRequest"));
                    continue;
                }
            };

            let header = raw_request_header(
                api_key,
                api_version,
                correlation_id,
                self.config.client_id.as_str(),
            );
            match transport::kp_send_request(conn, &header, request, api_version)
                .and_then(|()| transport::kp_get_response::<Resp>(conn, api_version))
            {
                Ok(resp) => return Ok(resp),
                Err(e) => last_err = Some(e.with_broker_context(&host, "RawProtocolRequest")),
            }
        }

        Err(last_err.unwrap_or_else(Error::no_host_reachable))
    }
}

fn raw_request_header(
    api_key: i16,
    api_version: i16,
    correlation_id: i32,
    client_id: &str,
) -> RequestHeader {
    RequestHeader::default()
        .with_client_id(Some(StrBytes::from_string(client_id.to_owned())))
        .with_request_api_key(api_key)
        .with_request_api_version(api_version)
        .with_correlation_id(correlation_id)
}

#[cfg(test)]
mod tests {
    use kafka_protocol::messages::{ApiKey, FetchSnapshotRequest, FetchSnapshotResponse};

    use super::*;
    use crate::protocol;

    fn assert_no_host<T>(result: &Result<T>) {
        assert!(matches!(
            result,
            Err(Error::Connection(
                crate::error::ConnectionError::NoHostReachable
            ))
        ));
    }

    #[test]
    fn raw_request_header_preserves_selected_protocol_fields() {
        let header = raw_request_header(59, 1, 42, "raw-client");

        assert_eq!(header.request_api_key, 59);
        assert_eq!(header.request_api_version, 1);
        assert_eq!(header.correlation_id, 42);
        assert_eq!(header.client_id.as_deref(), Some("raw-client"));
    }

    #[test]
    fn raw_protocol_request_surfaces_no_host_for_generated_internal_api() {
        let mut client = KafkaClient::new(vec![]);
        let request = FetchSnapshotRequest::default();

        let result: Result<FetchSnapshotResponse> = client.send_raw_protocol_request(
            ApiKey::FetchSnapshot as i16,
            protocol::API_VERSION_FETCH_SNAPSHOT,
            &request,
        );

        assert_no_host(&result);
    }
}
